### ISSUE TITLE
Exposing paths 

### ISSUE THREAD

**Issue by RomkaLTU** [GENL/matice#15]
### Expected behavior

Remove HTML comments from production build at least. 

### Current behavior

Comments injected 

```
Matice Laravel Translations generated
Used cached translations at: /home/forge/xxx/resources/assets/js/matice_translations.js 
```

I think it's giving everyone additional unesesery information and should be removed.

**Comment by GENL** [comment]
Noted. It will be removed,

**Comment by GENL** [comment]
Fixed. Will be merged in the upcoming release.

**Comment by mgralikowski** [comment]
The problem still exists. The path is exposed for the world. Generally, what it the purpose of this comments? Imo those are unnecessary bytes.

**Comment by GENL** [comment]
Do you have the latest version? The comment has been removed,

**Comment by mgralikowski** [comment]
Yes, I tried `dev-master` as well.

Localhost:
![image](https://user-images.githubusercontent.com/17027876/151774292-2a69530e-7076-42ba-80e6-fac77ad83562.png)
and it is ok.

But on prod I see sth like this:
![image](https://user-images.githubusercontent.com/17027876/151774638-352d2c19-e9eb-4139-8328-3caad9968103.png)

**Comment by GENL** [comment]
OMG! Let me remove it now,

**Comment by GENL** [comment]
Please upgrade to v1.1.7.
